### ISSUE TITLE
add documentation from binary zip

### ISSUE THREAD

**Issue by sl1pkn07** [AmusementClub/vcm#2]
Hi

vcm binary zip http://www.avisynth.nl/users/vcmohan/vcm/vcm.7z include the documentation for how use the plugin, but this is not included in the source code zip (or this repo)

is possible add it here?

greetings

**Comment by AkarinVS** [comment]
@theChaosCoder is it possible to include the docs in https://github.com/Vapoursynth-Plugins-Gitify/vcm ?

Thanks.

**Comment by theChaosCoder** [comment]
It's included in the release zip.
A docs folder is fine?

EDIT
https://github.com/Vapoursynth-Plugins-Gitify/vcm/tree/master/docs

**Comment by AkarinVS** [comment]
yeah, adding a docs folder is fine. thanks.
In this way, we can keep the source and docs in sync.
